SITE-23: Fixing form error not showing
OrchardCMS/OrchardCore.Commerce pull request #179
Opened 2022-09-15 15:43 UTC by DemeSzabolcs

SITE-23

2022-09-16 12:49 UTC, wAsnk approved these changes

2022-09-19 14:28 UTC, wAsnk requested changes

2022-09-19 16:51 UTC, wAsnk approved these changes

2022-09-19 16:53 UTC, wAsnk commented
@DAud-IcI Could you review and merge this?

2022-09-19 16:54 UTC, DAud-IcI commented
Ok, I will review it soon.

2022-09-19 18:29 UTC, DAud-IcI requested changes

2022-09-19 18:29 UTC, DAud-IcI commented on src/Modules/OrchardCore.Commerce/Assets/Scripts/stripe-card-form.js
> +
Would be better to simply `return` in the `if (error)`. Same below.

2022-09-19 18:29 UTC, DAud-IcI commented on src/Modules/OrchardCore.Commerce/Views/ShoppingCartWidgetPart.cshtml
> +@Model.ItemCount
The purpose of this is not really clear to me. I can't imagine a scenario where I'd want to customize just the text inside the circle. I could see wanting to customize the circle itself (e.g. adding a dropdown or hiding it). So I think the `<div class="shopping-cart-item-count text-white bg-danger text-center">` should be moved into this shape.

2022-09-19 18:29 UTC, DAud-IcI commented on src/Modules/OrchardCore.Commerce/Views/Widget__ShoppingCartWidget.cshtml
> +    <a asp-action="Index" asp-controller="ShoppingCart" asp-area="OrchardCore.Commerce" class="shopping-cart-link nav-link d-flex">
I think you don't need `asp-area` if the link points to the same module.

2022-09-19 22:11 UTC, merged