OCC-119: Tiered pricing
OrchardCMS/OrchardCore.Commerce pull request #354
Opened 2023-09-20 15:07 UTC by barthamark

OCC-119
Fixes #241

2023-09-21 14:10 UTC, DAud-IcI requested changes

2023-09-21 14:10 UTC, DAud-IcI commented on src/Modules/OrchardCore.Commerce/Views/TieredPricePart.cshtml
> +                <li>@tier.Quantity - @tier.UnitPrice</li>
This seems a bit obscure, I'd prefer to use a text like "Starting from {0} units".

Also `PriceTier.UnitPrice` is just a `decimal`, so we lose the expected currency formatting like how many decimal places should be displayed. Rather convert it into `Amount` so its `ToString()` overload can be used.

2023-09-21 14:10 UTC, DAud-IcI commented on test/OrchardCore.Commerce.Tests.UI/Tests/TieredPricePartTests/PersistenceTieredPriceTests.cs
> +                const string addPriceTierButtonXPath = "//div[contains(@class, 'add-price-tier-button')]";
Instead of XPath you can store only the class name and then use `By.ClassName()`

2023-09-21 14:10 UTC, DAud-IcI commented on test/OrchardCore.Commerce.Tests.UI/Tests/TieredPricePartTests/PersistenceTieredPriceTests.cs
> +                await context.ClickReliablyOnAsync(By.XPath("//a[. = 'Edit']"));
Isn't that just `By.LinkText("Edit")`?

2023-09-21 15:10 UTC, DAud-IcI commented on src/Modules/OrchardCore.Commerce/Recipes/OrchardCore.Commerce.Content.TestTieredPriceProduct.recipe.json
Could you also add a "OrchardCore.Commerce.Samples.TestTieredPriceProduct" recipe?

2023-09-22 09:04 UTC, barthamark commented on src/Modules/OrchardCore.Commerce/Recipes/OrchardCore.Commerce.Content.TestTieredPriceProduct.recipe.json
Don't you want me to add samples to the OrchardCore.Commerce.Samples.Product recipe? That also has samples for the variant product.

2023-09-23 01:22 UTC, DAud-IcI commented on src/Modules/OrchardCore.Commerce/Models/TieredPricePart.cs
> +        if (PriceTiers is { } tiers && tiers.Any(tier => tier.Quantity <= quantity))
You've added `PriceTiers != null` instead even though that's also always null. Why?

2023-09-23 01:34 UTC, DAud-IcI requested changes

2023-09-23 01:34 UTC, DAud-IcI commented on src/Modules/OrchardCore.Commerce/Recipes/OrchardCore.Commerce.Content.TestTieredPriceProduct.recipe.json
> +    },
I don't think you needed the whole step.

2023-09-23 14:37 UTC, barthamark commented on src/Modules/OrchardCore.Commerce/Models/TieredPricePart.cs
> +        if (PriceTiers is { } tiers && tiers.Any(tier => tier.Quantity <= quantity))
Hmm, I remembered Rider insisting but now I don't see it so probably I was hallucinating.

2023-09-23 21:47 UTC, merged