OCC-195: Boolean product attributes not stored in the order screen.
OrchardCMS/OrchardCore.Commerce pull request #371
Opened 2023-10-19 14:04 UTC by porgabi

OCC-195

Fixes #365

2023-10-20 13:47 UTC, porgabi commented on src/Modules/OrchardCore.Commerce/Services/ProductAttributeProvider.cs
> +#pragma warning restore CA1308 // Normalize strings to uppercase
Normalizing to uppercase doesn't work in this case:
![devenv_LyrfBdXAa3](https://github.com/OrchardCMS/OrchardCore.Commerce/assets/51411356/6eb195ca-13c5-4d59-8d50-7e0af616a01e)

2023-10-20 13:49 UTC, porgabi commented on src/Modules/OrchardCore.Commerce/Views/BooleanProductAttributeField.cshtml
> +<input type="hidden" name="line.Attributes[@index].Value" value="false" />
Ended up restoring this as without it the attribute does not show up at all due to the missing value.

2023-10-20 16:19 UTC, porgabi commented on src/Modules/OrchardCore.Commerce/Views/BooleanProductAttributeField.cshtml
> +<input type="hidden" name="line.Attributes[@index].Value" value="false" />
It was causing issues, but then it wasn't and now it isn't. It's weird. UI tests are passing so I suppose it's fine?

2023-10-20 18:56 UTC, DAud-IcI requested changes

2023-10-20 18:56 UTC, DAud-IcI commented on src/Modules/OrchardCore.Commerce/Models/ShoppingCartItem.cs
> +            .Where(attr => attr is TextProductAttributeValue)
It's better to use `.CastWhere<T>()` here.

2023-10-20 18:56 UTC, DAud-IcI commented on src/Modules/OrchardCore.Commerce/Models/ShoppingCartItem.cs
> +                attr => attr is NumericProductAttributeValue numericAttribute ? numericAttribute.Value.ToString() : null);
This too, should be handled by type specific providers.
Also for the boolean and numeric, you can get the same value with `attr.UntypedValue?.ToString()`.

2023-10-20 18:56 UTC, DAud-IcI commented on src/Modules/OrchardCore.Commerce/Views/BooleanProductAttributeValue.cshtml
> +    tag.InnerHtml.Append((settings.Label ?? attributeValue.FieldName) + ": " + (attributeValue.Value ? "Yes" : "No"));
Use string localization for the "Yes" and "No".

2023-10-20 18:56 UTC, DAud-IcI commented on src/Modules/OrchardCore.Commerce/Views/OrderPart_Edit.cshtml
>  @{
You should minimize business logic in cshtml. No static code analysis, error handling works differently, it's not a good time. I think almost the whole of this large code block should be in `OrderPartDisplayDriver.Edit()`

2023-10-20 18:56 UTC, DAud-IcI commented on test/OrchardCore.Commerce.Tests.UI/Tests/OrderTests/BehaviorOrderTests.cs
> +                await context.GoToAdminRelativeUrlAsync("/ContentTypes/AddFieldsTo/Product");
The `/ContentTypes/AddFieldsTo/` has been used a few times, please create an extension method for it.

2023-10-21 12:40 UTC, porgabi commented on src/Modules/OrchardCore.Commerce/Drivers/OrderPartDisplayDriver.cs
> +        ProcessAttributes(OrderLineItemViewModel lineItem, ProductPart productPart)
Regarding individual providers, do you mean creating 3 new providers that implement `IProductAttributeProvider` with their own `CreateFromValue()` and `Parse()` implementations?

2023-10-21 13:48 UTC, DAud-IcI commented on src/Modules/OrchardCore.Commerce/Drivers/OrderPartDisplayDriver.cs
> +        ProcessAttributes(OrderLineItemViewModel lineItem, ProductPart productPart)
The goal is that we shouldn't have separate variables/properties like `SelectedBooleanAttributes` or `availableBooleanAttributes`. (it's okay to have those in the field-specific views like BooleanProductAttributeField.cshtml and BooleanProductAttributeValue.cshtml)

The provider should interact with dictionaries keyed to the type it handles. So create 3 new providers that implement `IProductAttributeProvider` and wherever you have added type specific logic create a method and move the code to the matching provider. For example the `HandleSelectedBooleanAttributes` should be something like `BooleanProductAttributeProvider.HandleSelected()`.

2023-10-28 10:12 UTC, DAud-IcI requested changes

2023-10-28 10:12 UTC, DAud-IcI commented on src/Modules/OrchardCore.Commerce/Services/ProductAttributeService.cs
> +        var fieldName = partAndField[1];
We have an extension method for splitting a two-part string by a separator.
```suggestion
        var (partName, _, fieldName) = attributeName.Partition(".");
```

2023-10-28 10:12 UTC, DAud-IcI commented on src/Modules/OrchardCore.Commerce/Services/StripePaymentService.cs
> +            }
This can be converted into linq extensions which would be cleaner.

2023-10-28 10:16 UTC, DAud-IcI commented
I went ahead and committed the stuff mentioned above, as an apology for the late review.

2023-10-28 10:28 UTC, merged

2023-10-28 13:50 UTC, porgabi commented
Thanks! I think it wasn't very late, it's only been a few days, but appreciate it regardless! 😃