OCC-229: Inventory part with non-restricted product attributes can't be added to the cart
OrchardCMS/OrchardCore.Commerce pull request #421
Opened 2024-04-10 00:27 UTC by sarahelsaig

[OCC-229](https://lombiq.atlassian.net/browse/OCC-229)
Fixes #419

2024-04-12 19:41 UTC, DemeSzabolcs requested changes

2024-04-12 19:41 UTC, DemeSzabolcs commented on src/Modules/OrchardCore.Commerce.Inventory/Drivers/InventoryPartDisplayDriver.cs
> +                : currentSku;
Shouldn't `DefaultKey` should be used here? (Or the const should be removed) Because the const now is not used anywhere.

2024-04-12 19:41 UTC, DemeSzabolcs commented on src/Modules/OrchardCore.Commerce/Drivers/ProductPartDisplayDriver.cs
I reset the webapp, then tried to repro the problem with your changes (so there shouldn't be any repro): https://github.com/OrchardCMS/OrchardCore.Commerce/issues/419#issue-2232395838

I did these:
> Create a new content type.
Add Product part, Price part and Inventory part.
Add a text product attribute field (name doesn't matter).

![image](https://github.com/OrchardCMS/OrchardCore.Commerce/assets/80963259/b2d828f0-62a2-4d40-9625-b23f22c316e8)

But when I try to create a new item, I don't have SKU or Quantity: 
![image](https://github.com/OrchardCMS/OrchardCore.Commerce/assets/80963259/f5bed2c6-93e7-4ba9-84da-c43d4324dd69)

Also, I get this in the log: 
```
OrchardCore.ContentManagement.Display.ContentItemDisplayCoordinator|ERROR|IContentPartDisplayDriver thrown from OrchardCore.Commerce.Drivers.ProductPartDisplayDriver by ArgumentNullException System.ArgumentNullException: Value cannot be null. (Parameter 'key')
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at OrchardCore.Commerce.Drivers.ProductPartDisplayDriver.BuildViewModelAsync(ProductPartViewModel viewModel, ProductPart part) in G:\Work\OrchardCore.Commerce\src\Modules\OrchardCore.Commerce\Drivers\ProductPartDisplayDriver.cs:line 114
   at OrchardCore.Commerce.Drivers.ProductPartDisplayDriver.<>c__DisplayClass4_0.<<Edit>b__0>d.MoveNext() in G:\Work\OrchardCore.Commerce\src\Modules\OrchardCore.Commerce\Drivers\ProductPartDisplayDriver.cs:line 37
```

2024-04-14 16:33 UTC, DemeSzabolcs requested changes

2024-04-14 16:33 UTC, DemeSzabolcs commented on src/Modules/OrchardCore.Commerce/Drivers/ProductPartDisplayDriver.cs
I found another bug. When creating a content item for the first time, if you trying to save the item, without the SKU, you will get an error message (that's okay), but the SKU field disappears: 
![image](https://github.com/OrchardCMS/OrchardCore.Commerce/assets/80963259/909859d9-7f7a-4528-b968-530e02f1e2c9)

2024-04-14 16:44 UTC, sarahelsaig commented on src/Modules/OrchardCore.Commerce/Drivers/ProductPartDisplayDriver.cs
That sounded suspiciously unrelated, so I checked the current `main` branch and the same is true there. Not to expand the scope here, I will open a separate issue.

2024-04-14 18:06 UTC, DemeSzabolcs commented on src/Modules/OrchardCore.Commerce/Drivers/ProductPartDisplayDriver.cs
Alright!

2024-04-14 18:07 UTC, DemeSzabolcs approved these changes

2024-04-14 18:08 UTC, merged